# Generated by Django 6.0.6 on 2026-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_detallepedido_cantidad_kilos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo / Pago contra entrega'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito / Débito')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
