# Generated by Django 6.0.6 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_metodo_pago_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='precio_unitario',
            new_name='precio_por_kilo',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_producto_respaldo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de entrega'), ('EN_PROCESO', 'Preparando en bodega'), ('ENTREGADO', 'Entregado con éxito'), ('CANCELADO', 'Pedido cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_kilos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
        ),
    ]
