# Generated by Django 6.0.6 on 2026-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
